### ISSUE TITLE
baur status: passing a path as argument causes a panic

### ISSUE THREAD

**Issue by fho** [simplesurance/baur#265]
```
panic: path is empty

goroutine 1 [running]:
github.com/simplesurance/baur/v1/pkg/cfg.(*Task).addCfgFilepath(0xc0002cd760, 0x0, 0x0)
	github.com/simplesurance/baur/v1/pkg/cfg/task.go:22 +0x85
github.com/simplesurance/baur/v1/pkg/cfg.taskMerge(0x11a7440, 0xc0002cd760, 0xc0004c3c00, 0x30, 0x1188100, 0xc0001168c0, 0xc0001162e0, 0x20, 0x18)
	github.com/simplesurance/baur/v1/pkg/cfg/taskdef.go:26 +0x199
github.com/simplesurance/baur/v1/pkg/cfg.(*App).Merge(0xc0001180f0, 0xc0001162e0, 0x1188100, 0xc0001168c0, 0xc0002cb948, 0x0)
	github.com/simplesurance/baur/v1/pkg/cfg/app.go:139 +0x274
github.com/simplesurance/baur/v1/pkg/baur.(*Loader).fromCfg(0xc000118050, 0xc0001180f0, 0xc0001180f0, 0x0, 0x0)
	github.com/simplesurance/baur/v1/pkg/baur/loader.go:314 +0x19d
github.com/simplesurance/baur/v1/pkg/baur.(*Loader).AppPath(0xc000118050, 0xc0000a1220, 0x1a, 0xc0000a1220, 0x1a, 0xece980)
	github.com/simplesurance/baur/v1/pkg/baur/loader.go:221 +0x13d
github.com/simplesurance/baur/v1/pkg/baur.(*Loader).AppDirs(0xc000118050, 0xc000179a70, 0x1, 0x1, 0x9, 0xc00010faa0, 0x9c453e, 0xe67900, 0x0)
	github.com/simplesurance/baur/v1/pkg/baur/loader.go:196 +0x147
github.com/simplesurance/baur/v1/pkg/baur.(*Loader).apps(0xc000118050, 0xc0001180a0, 0x1, 0xc0001180a0, 0x0, 0x0, 0x65)
	github.com/simplesurance/baur/v1/pkg/baur/loader.go:293 +0x145
github.com/simplesurance/baur/v1/pkg/baur.(*Loader).LoadTasks(0xc000118050, 0xc0002f4780, 0x1, 0x1, 0x0, 0x0, 0x0, 0x4ac71a, 0xc00021fbb0)
	github.com/simplesurance/baur/v1/pkg/baur/loader.go:68 +0x9d
github.com/simplesurance/baur/v1/internal/command.(*runCmd).run(0xc0001d6600, 0xc0001d6600, 0xc0002f4780, 0x1, 0x1)
	github.com/simplesurance/baur/v1/internal/command/run.go:142 +0x433
github.com/spf13/cobra.(*Command).execute(0xc0001d6600, 0xc0002f4750, 0x1, 0x1, 0xc0001d6600, 0xc0002f4750)
	github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1700ea0, 0x173abe9, 0xfe96bc, 0x8)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/simplesurance/baur/v1/internal/command.Execute()
	github.com/simplesurance/baur/v1/internal/command/root.go:69 +0x286
main.main()
	command-line-arguments/main.go:6 +0x25
```

**Comment by fho** [comment]
issue does not exist in master, was only in a branch that was not merged
